name: sotu
channels:
  - conda-forge
  - nodefaults
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - brotli-python=1.2.0=py313h09d1b84_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - catalogue=2.0.10=py313h78bf25f_2
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py313hf46b229_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - cloudpathlib=0.23.0=pyhd8ed1ab_0
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - confection=0.1.5=pyhecae5ae_0
  - cpython=3.13.9=py313hd8ed1ab_101
  - cymem=2.0.11=py313h7033f15_1
  - cython-blis=1.3.0=py313ha014f3b_0
  - debugpy=1.8.17=py313h5d5ffb9_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - langcodes=3.4.1=pyhd8ed1ab_1
  - language-data=1.3.0=pyhff2d567_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libcblas=3.9.0=38_h0358290_openblas
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h767d61c_7
  - liblapack=3.9.0=38_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - marisa-trie=1.2.1=py313h7033f15_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py313h3dea7bd_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - murmurhash=1.0.13=py313h5d5ffb9_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.3.4=py313hf6604e3_0
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.2=pyh145f28c_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - preshed=3.0.10=py313h7033f15_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py313h54dd161_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.4=pyh3cfb1c2_0
  - pydantic-core=2.41.5=py313h843e2db_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.0=h9ebbce0_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.9=h4df99d1_101
  - python_abi=3.13=8_cp313
  - pyzmq=27.1.0=py312hfb55c3c_0
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - scikit-learn=1.7.2=py313h06d4379_0
  - scipy=1.16.3=py313h11c21cd_0
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhe01879c_1
  - smart-open=7.4.4=haacea70_0
  - smart_open=7.4.4=pyhcf101f3_0
  - spacy=3.8.7=py313hf0ab243_0
  - spacy-legacy=3.0.12=pyhd8ed1ab_0
  - spacy-loggers=1.0.5=pyhd8ed1ab_0
  - srsly=2.5.1=py313h46c70d0_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - thinc=8.3.6=py313hf0ab243_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.2=py313h07c4f96_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.20.0=pyhdb1f59b_0
  - typer-slim=0.20.0=pyhcf101f3_0
  - typer-slim-standard=0.20.0=h65a100f_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ujson=5.11.0=py313h5d5ffb9_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wasabi=1.1.3=pyhd8ed1ab_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - weasel=0.4.2=pyhd8ed1ab_0
  - wrapt=2.0.0=py313h07c4f96_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py313h54dd161_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - attrs==25.4.0
      - bertopic==0.17.3
      - contourpy==1.3.3
      - cycler==0.12.1
#      - en-core-web-sm==3.8.0
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - funcy==2.0
      - gensim==4.4.0
      - hdbscan==0.8.40
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - llvmlite==0.45.1
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - narwhals==2.10.2
      - nbformat==5.10.4
      - networkx==3.5
      - numba==0.62.1
      - numexpr==2.14.1
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - pandas==2.3.3
      - pillow==12.0.0
      - plotly==6.4.0
      - pyldavis==3.4.1
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - rpds-py==0.28.0
      - safetensors==0.6.2
      - seaborn==0.13.2
      - sentence-transformers==5.1.2
      - sympy==1.14.0
      - tokenizers==0.22.1
      - torch==2.9.0
      - transformers==4.57.1
      - triton==3.5.0
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
prefix: /srv/conda/envs/sotu
